teleop:
    move:
        type: topic
        message_type: "geometry_msgs/Twist"
        topic_name: cmd_vel
        axis_mappings:
            -
                axis: 1 # left thumb up-down
                target: linear.x
                scale: 1.0
                offset: 0.0
            - 
                axis: 2 # right thum left-right 
                target: angular.z
                scale: 1.0
                offset: 0.0
    button:
        type: topic
        message_type: "std_msgs/Empty"
        topic_name: button_a
        buttons: [0]
        axis_mappings: []
