# vi: ft=yaml

auto_save: true
display_label_popup: false
store_data: false
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

#DMS
confirm_delete: false
verify_mode: false
#/DMS

flags:
  - verified

# label_flags:
#   barcode:
#     - is_ua_lpn
#     - is_aafes_lpn
#     - cool
#     - misread

labels:
  - line
  - grass
  - sidewalk
  - pedestrian
  - vertical
  - sky
  - dirt
  - intersection

file_search: null
sort_labels: true
validate_label: null

default_shape_color: [0, 255, 0]
shape_color: manual  # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors:
  line: [255, 51, 0]
  grass: [102, 255, 51]
  sidewalk: [255, 255, 0]
  pedestrian: [230, 230, 0]
  vertical: [255, 128, 0]
  sky: [0, 0, 255]
  dirt: [255, 0, 255]
  intersection: [0, 204, 0]
  # banana: [204, 204, 0]
  # pallet: [255, 193, 51]
  # artag: [223, 255, 0]

shape:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 0]  # transparent
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 128]
  hvertex_fill_color: [255, 255, 255, 255]

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: false
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: false

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
# this affects vertex selection
# epsilon: 10.0
epsilon: 20.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close

shortcuts:
  close: null
  open: null
  open_dir: null
  quit: Ctrl+Q
  save: [Ctrl+S, W]
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: null

  open_next: [Space, Ctrl+Shift+D, Right]
  open_prev: [A, Ctrl+Shift+A, Left]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: [Ctrl+N, P]
  create_rectangle: [Ctrl+R, R]
  create_circle: null
  create_line: null
  create_point: K
  create_linestrip: null
  edit_polygon: [Ctrl+J, E]
  delete_polygon: Backspace
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, U]
  add_point_to_edge: Ctrl+Shift+P
  edit_label: L
  toggle_keep_prev_mode: null

  #DMS
  verify: V
  # verify_open_next: Ctrl+Return
  verify_open_next: Return
